# model
model: FrameByFrame

# device
cuda: True

# data path
type: data
vpath: 'data/Dataset/Dev/vfeat/resnet-101'
apath: 'data/Dataset/Dev/afeat/vggish-quant'

# name
ckpt_name: modelFrameByFramebatchSize64lr0.001vpathresnet-101apathvggish-quantmax_epochs100dropout_ratio0.0comment0.1pos/state_epoch100
