# model
model: ClassificationNet

# device
cuda: True

# data path
type: data

vpath: '/root/kyzhang/yjwang/InclusiveFL2/data/Dataset/Dev/vfeat/BeiTExtractor_noise'
apath: '/root/kyzhang/yjwang/InclusiveFL2/data/Dataset/Dev/afeat/Data2vecExtractor_noise'


# input size
v_input_size: 768
a_input_size: 768

# name

ckpt_name: modelClassificationNetbatchSize32lr0.001vpathBeiTExtractor_noiseapathData2vecExtractormax_epochs100dropout_ratio0commentbias50/state_epoch100
