# model
model: FrameByFrame

# device
cuda: True

# data path
type: data
vpath: 'data/Dataset/Dev/vfeat/BeiTExtractor'
apath: 'data/Dataset/Dev/afeat/vggish-quant'

# input size
v_input_size: 768
a_input_size: 128

# name
ckpt_name: modelFrameByFramebatchSize64lr0.001vpathBeiTExtractorapathvggish-quantmax_epochs100dropout_ratio0.0comment/state_epoch100
