# model
model: FrameByFrame

# device
cuda: True

# data path
type: data
vpath: 'data/Dataset/Dev/vfeat/BeiTExtractor'
apath: 'data/Dataset/Dev/afeat/Data2vecExtractor'

# input size
v_input_size: 768
a_input_size: 768

# name
ckpt_name: modelFrameByFramebatchSize64lr0.001vpathBeiTExtractorapathData2vecExtractormax_epochs200dropout_ratio0.3comment/state_epoch200
