# model
model: BeiTExtractor
pretrained: True # whether to load pretrained model
local_model: True # whether to load the local model params
local_path: /root/kyzhang/download/beit-base-patch16-224-pt22k-ft22k

# dir
dirname: data/Dataset/Train

# device
cuda: True # whether to use GPU

# noise
use_noise: True
mean: 1.8055
std: 7.62

# denoise
use_denoise: True